ALTER TABLE words ADD COLUMN rating_cefr TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN rating_freq TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN rating_rec  TEXT NOT NULL DEFAULT '';
